# Generated by Django 3.2.6 on 2021-08-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('achiev', models.CharField(default='', max_length=255)),
                ('achiev_year', models.IntegerField(default=2002)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('project', models.CharField(max_length=122)),
                ('msg', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('univercity', models.CharField(default='', max_length=255)),
                ('start_year', models.CharField(default='', max_length=12)),
                ('end_year', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('title', models.CharField(default='', max_length=255)),
                ('phone', models.CharField(default='', max_length=255)),
                ('email', models.EmailField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('home_desc', models.TextField(default='')),
                ('about_desc', models.TextField(default='')),
                ('year_experience', models.IntegerField(default=0)),
                ('completed_project', models.IntegerField(default=0)),
                ('companies_worked', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('company', models.CharField(default='', max_length=255)),
                ('start_year', models.CharField(default='', max_length=12)),
                ('end_year', models.CharField(default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('icon', models.CharField(default='', max_length=255)),
                ('ser1', models.CharField(default='', max_length=255)),
                ('ser2', models.CharField(default='', max_length=255)),
                ('ser3', models.CharField(default='', max_length=255)),
                ('ser4', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('link', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('image', models.ImageField(default='', upload_to='work/image')),
            ],
        ),
    ]
